# {{{ Exports

# Gobals exports
export TERM="screen-256color"
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export VISUAL=vim
export EDITOR="$VISUAL"
export KEYTIMEOUT=1
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=0'

# Path config
export PATH=$PATH:bin:~/bin:/usr/local/bin:/usr/local/sbin:/usr/local/mysql/bin:/usr/local/git/bin:/usr/bin:/bin:/usr/sbin:/sbin
export PATH="/usr/local/opt/gnu-tar/libexec/gnubin:$PATH"

# }}}
# {{{ Sourcings

# Sourcing internal stuff
source $HOME/.dotfiles/zsh/aliases
source $HOME/.dotfiles/zsh/functions

# Sourcing external plugins stuff
source $HOME/.dotfiles/zsh/plugins/explicit_aliases.sh
source $HOME/.dotfiles/zsh/plugins/mandatory_aliases.sh
source $HOME/.dotfiles/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source $HOME/.dotfiles/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# }}}
# {{{ Misc tweaks and hacks

# Allow completing of the remainder of a command
bindkey "^N" insert-last-word

bindkey -v
bindkey '^R' history-incremental-search-backward

# Vi mode
bindkey -v

# Save a ton of history
HISTSIZE=20000
HISTFILE=~/.zsh_history
SAVEHIST=20000

# Enable completion
autoload -U compinit
compinit -u

# Disable flow control commands (keeps C-s from freezing everything)
stty start undef
stty stop undef

# }}}
# {{{ Pure Prompt config

# Prompt pure setup and conf
autoload -U promptinit && promptinit
prompt pure

# }}}
# {{{ solarized dircolors config

# Solarized dircolors setup
eval $(gdircolors ~/.dotfiles/zsh/plugins/dircolors-solarized/dircolors.256dark)

# }}}
# {{{ solarized dircolors config
export BAT_THEME="TwoDark"
# }}}
# {{{ Allow overriden .zshrc

# Load local conf if present
[[ -f ~/.zshrc.local ]] && source ~/.zshrc.local

# }}}
