# {{{ Exports

# Gobals exports
export TERM="screen-256color"
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export VISUAL=vim
export EDITOR="$VISUAL"
export KEYTIMEOUT=1
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=0'

# For compilers to find zlib you may need to set:
export LDFLAGS="${LDFLAGS} -L/usr/local/opt/zlib/lib"
export CPPFLAGS="${CPPFLAGS} -I/usr/local/opt/zlib/include"

# For pkg-config to find zlib you may need to set:
export PKG_CONFIG_PATH="${PKG_CONFIG_PATH} /usr/local/opt/zlib/lib/pkgconfig"

eval "$(pyenv init -)"

# Path config
export PATH=$PATH:bin:~/bin:/usr/local/bin:/usr/local/sbin:/usr/local/mysql/bin:/usr/local/git/bin:/usr/bin:/bin:/usr/sbin:/sbin
export PATH="/usr/local/opt/gnu-tar/libexec/gnubin:$PATH"
# export PATH="$PATH:/Users/adrien/Library/Python/3.7/bin"

# export VIRTUALENVWRAPPER_PYTHON=/usr/local/Cellar/python/3.7.0/bin/python3
export WORKON_HOME=$HOME/.virtualenvs
source /usr/local/bin/virtualenvwrapper.sh

# }}}
# {{{ Sourcings

# Sourcing internal stuff
source $HOME/.dotfiles/zsh/aliases
source $HOME/.dotfiles/zsh/functions

# Sourcing external plugins stuff
source $HOME/.dotfiles/zsh/plugins/explicit_aliases.sh
source $HOME/.dotfiles/zsh/plugins/mandatory_aliases.sh
source $HOME/.dotfiles/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source $HOME/.dotfiles/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# }}}
# {{{ Misc tweaks and hacks

# Allow completing of the remainder of a command
bindkey "^N" insert-last-word

bindkey -v
bindkey '^R' history-incremental-search-backward

# Vi mode
bindkey -v

# Save a ton of history
HISTSIZE=20000
HISTFILE=~/.zsh_history
SAVEHIST=20000

# Enable completion
autoload -U compinit
compinit -u

# Disable flow control commands (keeps C-s from freezing everything)
stty start undef
stty stop undef

# }}}
# {{{ Pure Prompt config

# Prompt pure setup and conf
autoload -U promptinit && promptinit
prompt pure

# }}}
# {{{ solarized dircolors config

# Solarized dircolors setup
eval $(gdircolors ~/.dotfiles/zsh/plugins/dircolors-solarized/dircolors.256dark)

# }}}
# {{{ solarized dircolors config
export BAT_THEME="TwoDark"
# }}}
# {{{ Allow overriden .zshrc

# Load local conf if present
[[ -f ~/.zshrc.local ]] && source ~/.zshrc.local

# }}}
if [ /usr/local/bin/kubectl ]; then source <(kubectl completion zsh); fi

# tabtab source for serverless package
# uninstall by removing these lines or running `tabtab uninstall serverless`
[[ -f /Users/adrien/dev/axa/datastore/node_modules/tabtab/.completions/serverless.zsh ]] && . /Users/adrien/dev/axa/datastore/node_modules/tabtab/.completions/serverless.zsh
# tabtab source for sls package
# uninstall by removing these lines or running `tabtab uninstall sls`
[[ -f /Users/adrien/dev/axa/datastore/node_modules/tabtab/.completions/sls.zsh ]] && . /Users/adrien/dev/axa/datastore/node_modules/tabtab/.completions/sls.zsh
# tabtab source for slss package
# uninstall by removing these lines or running `tabtab uninstall slss`
[[ -f /Users/adrien/dev/axa/datastore/node_modules/tabtab/.completions/slss.zsh ]] && . /Users/adrien/dev/axa/datastore/node_modules/tabtab/.completions/slss.zshexport PATH="/usr/local/opt/terraform@0.11/bin:$PATH"

autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /usr/local/bin/terraform terraform

export GOPATH=$HOME/go
export AWS_SDK_LOAD_CONFIG=True
